spring:
  datasource:
    url: jdbc:mysql://local-mysql:3306/domedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin
    password: in2pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT}

app:
  url:
    api: ${APP_URL_API}
    wca-baseurl: ${WALLET_WCA_URL}

# Logging configuration
logging:
  level:
    # Set the log level for the entire application
    root: INFO
    # Set log level for specific packages or classes
    es.in2.wallet.service: DEBUG
    es.in2.wallet.util: DEBUG

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /spring-ui
    tags-sorter: alpha
    operations-sorter: method

in2:
  openapi:
    local-url: ${APP_URL_API}