spring:
  application:
    name: Wallet API
  datasource:
    url: jdbc:mysql://localhost:3309/domedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin
    password: in2pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8088

app:
  url:
    api: http://localhost:8088
    wca-baseurl: http://localhost:8083

# Logging configuration
logging:
  level:
    # Set the log level for the entire application
    root: INFO
    # Set log level for specific packages or classes
    es.in2.wallet.service: DEBUG
    es.in2.wallet.util: DEBUG

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /spring-ui
    tags-sorter: alpha
    operations-sorter: method

in2:
  openapi:
    local-url: http://localhost:8088