spring:
  application:
    name: WalletAPI
  datasource:
    url: jdbc:mysql://localhost:3309/domedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin
    password: in2pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084

in2:
  openapi:
    local-url: http://localhost:8084
    dev-url: http://localhost:8084 # TODO - Change

app:
  url:
    api: http://localhost:8084
    verifiable-credential-service-baseurl: http://localhost:8083/api/credentials
    siop-service-baseurl: http://localhost:8083/api/siop

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true

# Logging configuration
logging:
  level:
    # Set the log level for the entire application
    root: INFO
    # Set log level for specific packages or classes
    es.in2.wallet.service: DEBUG
    es.in2.wallet.util: DEBUG